# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_version = ">= 1.0.0"
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

provider "google" {
  project     = "dbt-feature-store"
  region      = "europe-central2"
}

